// Bundles the decode worker into a module that exports its source as a string.
//
// The worker cannot be a second entrypoint: `Bun.build` leaves
// `new Worker(new URL('./x.ts', import.meta.url))` exactly as written and emits
// no chunk for it, so at runtime the window would ask for a .ts file. A source
// string works in both bundlers the window is built with -- electrobun's
// Bun.build and Vite -- and needs no import attributes, which the two spell
// differently.
//
// Run by `dev`, `dev/ui`, `build`, `typecheck` and `test`; the output is
// git-ignored.

import { dirname, join } from 'node:path';

const packageRoot = join(dirname(import.meta.path), '..');
const entrypoint = join(packageRoot, 'src/webview/decodeWorker.ts');
const output = join(packageRoot, 'src/webview/.generated/decodeWorkerSource.ts');

const built = await Bun.build({
    entrypoints: [entrypoint],
    target: 'browser',
    format: 'esm',
    minify: true,
});

if (!built.success) {
    for (const log of built.logs) {
        console.error(log.message);
    }
    throw new Error('could not bundle the decode worker');
}

const source = await built.outputs[0]!.text();
await Bun.write(
    output,
    `// Generated by scripts/buildDecodeWorker.ts from src/webview/decodeWorker.ts.
// Do not edit: rebuild it instead.
/* eslint-disable */
export const DECODE_WORKER_SOURCE = ${JSON.stringify(source)};
`
);

console.log(`decode worker: ${(source.length / 1024).toFixed(1)} kB bundled into ${output}`);
